# Step 1. EDA

In [1]:
import pandas as pd
import os.path

In [2]:
df = pd.read_csv('data/train.csv', nrows=5000,
                 dtype={'toxic':'int8',
                        'severe_toxic':'int8',
                        'obscene':'int8', 
                        'threat':'int8',
                        'insult':'int8',
                        'identity_hate':'int8'}).sample(frac=1, random_state=66136).reset_index(drop=True)

In [3]:
pd.set_option('display.max_colwidth', None)

In [4]:
df.head()

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0b2364dbd14d7571,"""\r\n\r\nError in """"Lindeberg condition""""?\r\n\r\nI suspect the Lindeberg condition in the section discussing non-identically distributed random variables might be incorrect. Possibly there should be an average instead of a plain sum, or someting like that. I suspect that in the current form, the condition is essentially never satisfied. Not sure about this, though. I'll check this if I find the original reference. 130.231.89.82 """,0,0,0,0,0,0
1,0d189e22a297a2d9,"""Hmmmmmm. perhaps the last statement needs some rewording after all.Maybe """"Dalit Christians do not hold as much arable land as the upper-caste Christians"""" is better.\r\n""",0,0,0,0,0,0
2,0a16cfdad14faeb4,just aying thanks for your input on the Baritone guitar page. that was quitehelpful. ),0,0,0,0,0,0
3,015d1b0bb4cc744d,"Dictionaries\r\n\r\nHow dare you call my contribution spam!!! I am a Kurd and I made a lsit of kurdish dictionaries. you bloody turkish nationalist and atoricity commiting bone breaking Nazi. watch out folk this slimy Turk is trying to censor the internet this is not undemocratic Turkey here, no prison cells in wikipedia you stupid Turk! And you buggers want membership to the EEC",1,0,1,0,1,1
4,0b98ed0fc049ca8b,make that 21 cos u removed my do not vandalize message,0,0,0,0,0,0

In [5]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             5000 non-null   object
 1   comment_text   5000 non-null   object
 2   toxic          5000 non-null   int8
 3   severe_toxic   5000 non-null   int8
 4   obscene        5000 non-null   int8
 5   threat         5000 non-null   int8
 6   insult         5000 non-null   int8
 7   identity_hate  5000 non-null   int8
dtypes: int8(6), object(2)
memory usage: 2.8 MB

In [6]:
import spacy

In [7]:
nlp = spacy.load('en_core_web_sm') # Model needs to downloaded: python -m spacy download en_core_web_sm

In [8]:
def lower_replace(series):
    res = series.str.lower()
    res = res.str.replace(r'[^\w\s]', '', regex=True)
    res = res.str.replace(r'\d','', regex=True)
    res = res.str.replace('\n', ' ', regex=False)
    res = res.str.replace('\t', ' ', regex=False)
    res = res.str.replace('\r', ' ', regex=False)
    res = res.str.replace(r'\s+', ' ', regex=True)
    return res
    
def tokenize_lemmatize(text, remove_stop=True):
    doc = nlp(text)
    norm = []
    if remove_stop:
        norm = [token.lemma_ for token in doc if not token.is_stop and (len(token.text) > 1 or token.text=='i')]
    else:
        norm = [token.lemma_ for token in doc if len(token.text) > 1 or token.text=='i']
    return ' '.join(norm)

In [9]:
def normalize_text(series, remove_stop_words=True):
    res = lower_replace(series)
    res = res.apply(tokenize_lemmatize, remove_stop=remove_stop_words)
    return res

In [10]:
if os.path.isfile('text_clean_nostop.pkl'):
    df.insert(loc=2,column='text_clean_nostop',value=pd.read_pickle('text_clean_nostop.pkl'))
else:
    df.insert(loc=2,column='text_clean_nostop',value=normalize_text(df.comment_text))    
    pd.to_pickle(df.text_clean_nostop, 'text_clean_nostop.pkl')

if os.path.isfile('text_clean_withstop.pkl'):
    df.insert(loc=3,column='text_clean_withstop',value=pd.read_pickle('text_clean_withstop.pkl'))    
else:
    df.insert(loc=3,column='text_clean_withstop',value=normalize_text(df.comment_text, remove_stop_words=False))
    pd.to_pickle(df.text_clean_withstop, 'text_clean_withstop.pkl')

In [11]:
df.head(5)

,id,comment_text,text_clean_nostop,text_clean_withstop,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,0b2364dbd14d7571,"""\r\n\r\nError in """"Lindeberg condition""""?\r\n\r\nI suspect the Lindeberg condition in the section discussing non-identically distributed random variables might be incorrect. Possibly there should be an average instead of a plain sum, or someting like that. I suspect that in the current form, the condition is essentially never satisfied. Not sure about this, though. I'll check this if I find the original reference. 130.231.89.82 """,error lindeberg condition suspect lindeberg condition section discuss nonidentically distribute random variable incorrect possibly average instead plain sum somete like suspect current form condition essentially satisfied sure ill check find original reference,error in lindeberg condition I suspect the lindeberg condition in the section discuss nonidentically distribute random variable might be incorrect possibly there should be an average instead of plain sum or somete like that I suspect that in the current form the condition be essentially never satisfied not sure about this though ill check this if I find the original reference,0,0,0,0,0,0
1,0d189e22a297a2d9,"""Hmmmmmm. perhaps the last statement needs some rewording after all.Maybe """"Dalit Christians do not hold as much arable land as the upper-caste Christians"""" is better.\r\n""",hmmmmmm statement need rewording allmaybe dalit christian hold arable land uppercaste christians well,hmmmmmm perhaps the last statement need some rewording after allmaybe dalit christian do not hold as much arable land as the uppercaste christians be well,0,0,0,0,0,0
2,0a16cfdad14faeb4,just aying thanks for your input on the Baritone guitar page. that was quitehelpful. ),aye thank input baritone guitar page quitehelpful,just aye thank for your input on the baritone guitar page that be quitehelpful,0,0,0,0,0,0
3,015d1b0bb4cc744d,"Dictionaries\r\n\r\nHow dare you call my contribution spam!!! I am a Kurd and I made a lsit of kurdish dictionaries. you bloody turkish nationalist and atoricity commiting bone breaking Nazi. watch out folk this slimy Turk is trying to censor the internet this is not undemocratic Turkey here, no prison cells in wikipedia you stupid Turk! And you buggers want membership to the EEC",dictionarie dare contribution spam kurd lsit kurdish dictionarie bloody turkish nationalist atoricity commit bone break nazi watch folk slimy turk try censor internet undemocratic turkey prison cell wikipedia stupid turk bugger want membership eec,dictionarie how dare you call my contribution spam I be kurd and I make lsit of kurdish dictionarie you bloody turkish nationalist and atoricity commit bone break nazi watch out folk this slimy turk be try to censor the internet this be not undemocratic turkey here no prison cell in wikipedia you stupid turk and you bugger want membership to the eec,1,0,1,0,1,1
4,0b98ed0fc049ca8b,make that 21 cos u removed my do not vandalize message,cos remove vandalize message,make that cos remove my do not vandalize message,0,0,0,0,0,0

# Step 2. Vectorization

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
def create_tfidf_df(series, ngram_range=(1,2)):
    tv = TfidfVectorizer(ngram_range=ngram_range)
    tfidf = tv.fit_transform(series)
    tfidf_df = pd.DataFrame.sparse.from_spmatrix(tfidf, columns=tv.get_feature_names_out())
    return tfidf_df

In [14]:
def create_countv_df(series, ngram_range=(1,2)):
    cv = CountVectorizer(ngram_range=ngram_range)
    countv = cv.fit_transform(series)
    countv_df = pd.DataFrame.sparse.from_spmatrix(countv, columns=cv.get_feature_names_out())
    return countv_df

In [15]:
if not os.path.isfile('tfidf_nostop_df.pkl'):
    pd.to_pickle(create_tfidf_df(df.text_clean_nostop,ngram_range=(1,2)),'tfidf_nostop_df.pkl')

if not os.path.isfile('tfidf_withstop_df.pkl'):
    pd.to_pickle(create_tfidf_df(df.text_clean_withstop, ngram_range=(1,2)),'tfidf_withstop_df.pkl')

tfidf_nostop_df = pd.read_pickle('tfidf_nostop_df.pkl')
tfidf_withstop_df = pd.read_pickle('tfidf_withstop_df.pkl')

In [16]:
if not os.path.isfile('countv_nostop_df.pkl'):
    pd.to_pickle(create_countv_df(df.text_clean_nostop,ngram_range=(1,2)), 'countv_nostop_df.pkl')

if not os.path.isfile('countv_withstop_df.pkl'):
    pd.to_pickle(create_countv_df(df.text_clean_withstop, ngram_range=(1,2)), 'countv_withstop_df.pkl')
 
countv_nostop_df = pd.read_pickle('countv_nostop_df.pkl') 
countv_withstop_df = pd.read_pickle('countv_withstop_df.pkl')

# Step 3.Train

In [17]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

In [18]:
X_df = pd.read_pickle('countv_nostop_df.pkl')

In [19]:
y = df[['toxic','severe_toxic','obscene','threat','insult', 'identity_hate']]
#y

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X_df, y, test_size=0.2, random_state=42)

model=OneVsRestClassifier(MultinomialNB())
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, zero_division=0))

Accuracy: 0.859
              precision    recall  f1-score   support

           0       0.54      0.54      0.54       102
           1       0.10      0.22      0.13         9
           2       0.63      0.58      0.60        64
           3       0.00      0.00      0.00         5
           4       0.50      0.43      0.46        67
           5       0.27      0.27      0.27        15

   micro avg       0.48      0.48      0.48       262
   macro avg       0.34      0.34      0.33       262
weighted avg       0.51      0.48      0.50       262
 samples avg       0.05      0.05      0.04       262

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X_df, y, test_size=0.2, random_state=42)

model = OneVsRestClassifier(LogisticRegression(solver='lbfgs', max_iter=500))
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred, zero_division=0))

Accuracy: 0.898
              precision    recall  f1-score   support

           0       0.85      0.44      0.58       102
           1       0.50      0.33      0.40         9
           2       1.00      0.48      0.65        64
           3       0.00      0.00      0.00         5
           4       0.84      0.39      0.53        67
           5       0.67      0.13      0.22        15

   micro avg       0.86      0.41      0.55       262
   macro avg       0.64      0.30      0.40       262
weighted avg       0.84      0.41      0.55       262
 samples avg       0.04      0.03      0.04       262

## Neural networks

In [22]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, GlobalAveragePooling1D, Dropout
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score

C:\Users\qtern\anaconda3\envs\coursework\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

In [23]:
MAX_FEATURES = 10000  # размер словаря
MAX_LEN = 200         # максимальная длина последовательности
EMBEDDING_DIM = 100   # размерность эмбеддингов
BATCH_SIZE = 32
EPOCHS = 20

In [24]:
target_columns = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']
y = df[target_columns].values
texts = df['text_clean_nostop'].values
X_train, X_test, y_train, y_test = train_test_split(texts, y, test_size=0.2, random_state=42, stratify=y.any(axis=1))

In [25]:
tokenizer = Tokenizer(num_words=MAX_FEATURES, oov_token='<OOV>')
tokenizer.fit_on_texts(X_train)

In [26]:
X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

In [27]:
X_train_pad = pad_sequences(X_train_seq, maxlen=MAX_LEN, padding='post', truncating='post')
X_test_pad = pad_sequences(X_test_seq, maxlen=MAX_LEN, padding='post', truncating='post')

In [28]:
def create_fasttext_model(vocab_size, embedding_dim, max_len, output_dim):
    model = Sequential([
        Embedding(input_dim=vocab_size, 
                 output_dim=embedding_dim,
                 name='embedding'),
        
        GlobalAveragePooling1D(name='global_avg_pooling'),
        
        Dense(128, activation='relu', name='dense_1'),
        Dropout(0.5, name='dropout_1'),
        
        Dense(64, activation='relu', name='dense_2'),
        Dropout(0.3, name='dropout_2'),
        
        Dense(output_dim, activation='sigmoid', name='output')
    ])
    
    return model

In [29]:
vocab_size = min(MAX_FEATURES, len(tokenizer.word_index) + 1)
output_dim = len(target_columns)

In [30]:
model = create_fasttext_model(vocab_size, EMBEDDING_DIM, MAX_LEN, output_dim)
model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [31]:
early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True,
    verbose=1
)
reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=3,
    min_lr=1e-7,
    verbose=1
)
history = model.fit(
    X_train_pad, y_train,
    batch_size=BATCH_SIZE,
    epochs=EPOCHS,
    validation_data=(X_test_pad, y_test),
    callbacks=[early_stopping, reduce_lr],
    verbose=1
)

Epoch 1/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.5610 - loss: 0.2283 - val_accuracy: 0.9930 - val_loss: 0.1545 - learning_rate: 0.0010
Epoch 2/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.6447 - loss: 0.1705 - val_accuracy: 0.9930 - val_loss: 0.1453 - learning_rate: 0.0010
Epoch 3/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7107 - loss: 0.1610 - val_accuracy: 0.9930 - val_loss: 0.1417 - learning_rate: 0.0010
Epoch 4/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.7630 - loss: 0.1518 - val_accuracy: 0.9930 - val_loss: 0.1422 - learning_rate: 0.0010
Epoch 5/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8167 - loss: 0.1463 - val_accuracy: 0.9930 - val_loss: 0.1347 - learning_rate: 0.0010
Epoch 6/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8388 - loss: 0.1423 - val_accuracy: 0.9930 - val_loss: 0.1306 - learning_rate: 0.0010
Epoch 7/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8665 - loss: 0.1398 - val_accuracy: 0.9930 - val_loss: 0.1312 - learning_rate: 0.0010
Epoch 8/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8763 - loss: 0.1276 - val_accuracy: 0.9930 - val_loss: 0.1231 - learning_rate: 0.0010
Epoch 9/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.8840 - loss: 0.1247 - val_accuracy: 0.9930 - val_loss: 0.1090 - learning_rate: 0.0010
Epoch 10/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9440 - loss: 0.1282 - val_accuracy: 0.9930 - val_loss: 0.1200 - learning_rate: 0.0010
Epoch 11/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9200 - loss: 0.1104 - val_accuracy: 0.9930 - val_loss: 0.1052 - learning_rate: 0.0010
Epoch 12/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9682 - loss: 0.1068 - val_accuracy: 0.9930 - val_loss: 0.1085 - learning_rate: 0.0010
Epoch 13/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9693 - loss: 0.0914 - val_accuracy: 0.9930 - val_loss: 0.1193 - learning_rate: 0.0010
Epoch 14/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9700 - loss: 0.0949 - val_accuracy: 0.9930 - val_loss: 0.1000 - learning_rate: 0.0010
Epoch 15/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9693 - loss: 0.0890 - val_accuracy: 0.9930 - val_loss: 0.0907 - learning_rate: 0.0010
Epoch 16/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9883 - loss: 0.0954 - val_accuracy: 0.9930 - val_loss: 0.1116 - learning_rate: 0.0010
Epoch 17/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9845 - loss: 0.0799 - val_accuracy: 0.9930 - val_loss: 0.0887 - learning_rate: 0.0010
Epoch 18/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9870 - loss: 0.0862 - val_accuracy: 0.9930 - val_loss: 0.1141 - learning_rate: 0.0010
Epoch 19/20
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9768 - loss: 0.0796 - val_accuracy: 0.9930 - val_loss: 0.0896 - learning_rate: 0.0010
Epoch 20/20
118/125 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9761 - loss: 0.0693
Epoch 20: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.
125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9847 - loss: 0.0736 - val_accuracy: 0.9930 - val_loss: 0.0907 - learning_rate: 0.0010
Restoring model weights from the end of the best epoch: 17.

In [32]:
test_loss, test_accuracy = model.evaluate(X_test_pad, y_test, verbose=0)

In [33]:
y_pred = model.predict(X_test_pad)
y_pred_binary = (y_pred > 0.5).astype(int)

32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

In [34]:
print(classification_report(y_test, y_pred_binary, zero_division=0))

              precision    recall  f1-score   support

           0       0.84      0.38      0.52       101
           1       0.00      0.00      0.00         9
           2       0.82      0.51      0.63        53
           3       0.00      0.00      0.00         2
           4       0.59      0.35      0.44        49
           5       0.00      0.00      0.00        10

   micro avg       0.77      0.37      0.50       224
   macro avg       0.37      0.21      0.26       224
weighted avg       0.70      0.37      0.48       224
 samples avg       0.03      0.03      0.03       224

In [35]:
print(accuracy_score(y_test, y_pred_binary))

0.896

In [ ]:
from transformers import TFRobertaForSequenceClassification, RobertaTokenizer

MODEL_NAME = "roberta-base"
MAX_LEN = 128
BATCH_SIZE = 16
EPOCHS = 3
LR = 2e-5
TEXT_COL = "comment_text"
#TEXT_COL = "roberta_text" <- написать нормализацию текста для Roberta
LABEL_COLS = ["toxic","severe_toxic","obscene","threat","insult","identity_hate"]
NUM_LABELS = len(LABEL_COLS)

texts = df[TEXT_COL].astype(str).tolist()
labels = df[LABEL_COLS].values.astype("float32")

X_train, X_val, y_train, y_val = train_test_split(
    texts, labels, test_size=0.2, random_state=42
)

tokenizer = RobertaTokenizer.from_pretrained(MODEL_NAME)

def encode(texts):
    return tokenizer(
        texts,
        truncation=True,
        padding="max_length",
        max_length=MAX_LEN,
        return_tensors="tf"
    )

train_enc = encode(X_train)
val_enc = encode(X_val)

model = TFRobertaForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=NUM_LABELS,
    problem_type="multi_label_classification",
    from_pt=True,             
    use_safetensors=False
)

model.compile(
    optimizer="adam",  
    loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
    metrics=["accuracy"]
)
tf.keras.backend.set_value(model.optimizer.learning_rate, LR)
model.summary()

model.fit(
    dict(train_enc),
    y_train,
    validation_data=(dict(val_enc), y_val),
    batch_size=BATCH_SIZE,
    epochs=EPOCHS
)

All PyTorch model weights were used when initializing TFRobertaForSequenceClassification.

Some weights or buffers of the TF 2.0 model TFRobertaForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.dense.weight', 'classifier.dense.bias', 'classifier.out_proj.weight', 'classifier.out_proj.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Model: "tf_roberta_for_sequence_classification_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 roberta (TFRobertaMainLaye  multiple                  124055040
 r)

 classifier (TFRobertaClass  multiple                  595206
 ificationHead)

=================================================================
Total params: 124650246 (475.50 MB)
Trainable params: 124650246 (475.50 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/3
WARNING:tensorflow:From C:\Users\qtern\anaconda3\envs\coursework\Lib\site-packages\tf_keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From C:\Users\qtern\anaconda3\envs\coursework\Lib\site-packages\tf_keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

 19/250 [=>............................] - ETA: 15:34 - loss: 0.4930 - accuracy: 0.5559